### ISSUE TITLE
CI Build improvements

### ISSUE THREAD

**Issue by JanStevens** [torba-rb/torba-rails#5]
Hello,

In our CI Setup we first install the gems and precompile our assets, the resulting files are then shared between our parallel test executors (so they don't have to reinstall gems/build assets).

The disadvantage here is that I must share the complete torba cache and torba path else torba complains it is not run (even when the assets are precompiled already).

Would it be possible to disable or let torba known that its job is already done?
This would help speeding up the CI builds (since they don't have to download the complete assets path)

**Comment by nashbridges** [comment]
As far as I understand, you bypass asset pipeline during tests. If so, the simplest solution would be to [disable serving static assets](https://github.com/torba-rb/torba-rails/blob/master/lib/torba/rails.rb#L8) in config/test.rb

**Comment by JanStevens** [comment]
Shouldn't that be the other way around? From the rails docs

```
config.public_file_server.enabled configures Rails to serve static files from the public directory. This option defaults to true, but in the production environment it is set to false because the server software (e.g. NGINX or Apache) used to run the application should serve static files instead. If you are running or testing your app in production mode using WEBrick (it is not recommended to use WEBrick in production) set the option to true. Otherwise, you won't be able to use page caching and request for files that exist under the public directory.
```

So I want to serve my assets during specs from the public dir since they are precompiled, then I should enable this option. But this also forces torba to start.
Maybe add an option do disable in specific environments?

**Comment by nashbridges** [comment]
Unfortunately, there's no special config for asset pipeline only, and I
don't want to introduce it either.

One solution would be to launch separate webrick instance (or even
nodejs/go process) for serving files. Another solution is to symlink .torba
directory into every worker's env.

11 жовт. 2016 р. 10:02 пп "Jan Stevens" <notifications@github.com> пише:

**Comment by JanStevens** [comment]
Right now we `fixed` it by passing all the assets (downloaded and packed) from torba through our different testing stages. The main issue is that this is quite big and slow to send around (couple of 100 Mb)

What about an ENV variable that overwrite the `Torba.verify` check? `TORBA_DISABLE_VERIFY` or something?

Regards

**Comment by nashbridges** [comment]
I'm not sure why do you need to copy files. Do you use different machines,
so that symlink/shared directory doesn't work?

12 жовт. 2016 р. 9:13 дп "Jan Stevens" <notifications@github.com> пише:

**Comment by JanStevens** [comment]
Docker containers...
But we worked around it

**Comment by nashbridges** [comment]
I'm not familiar with Docker. Are you saying that mounting host's .torba is
not possible (https://docs.docker.com/engine/tutorials/dockervolumes/) or
it doesn't give you the performance boost?

12 жовт. 2016 р. 10:37 дп "Jan Stevens" <notifications@github.com> пише:

**Comment by nashbridges** [comment]
@JanStevens perhaps this is too old to be still relevant, but I've explained in Readme how to disable the gem in such a case, see https://github.com/torba-rb/torba-rails#disable-torba-rails.
